### ISSUE TITLE
When hosting HTTPS (self-signed cert), file downloads over 2GB fail at exactly 2GB

### ISSUE THREAD

**Issue by Stephen-Seo** [ourway/webfsd#2]
Discovered this while temporarily sending video podcasts to my phone over https: when webfsd is hosting a directory with HTTPS (using a self-signed cert), any file over 2GB will fail at exactly 2GB, leaving an incomplete file of size exactly 2GB on the client. This bug does not occur when using plain HTTP.

This occurs on an ArchLinux 64-bit host using webfs version 1.21 ([1.21-14 from the ArchLinux community repo](https://www.archlinux.org/packages/community/x86_64/webfs/)).

**Comment by Stephen-Seo** [comment]
I've discovered that when downloading a file over HTTPS, the `lseek` function is not required (reading from the file advances the position of the next read). I haven't tested the `STATE_WRITE_RANGES` case as I'm not sure what that is, but I'm pretty sure that that case also uses the `ssl_blk_write` function during use of HTTPS. Can you explain to me what that case is for, or if you can, test the commit to see if it works with this change? It would break things if the same file needs to be read from again from the beginning, and if that is the case it would probably be better to check when to seek to the beginning to do the `lseek`.

**Comment by Stephen-Seo** [comment]
I forgot to mention that I removed the `lseek` because it constantly did a seek on the file to send via an absolute position of the file as an offset from the beginning. Since the offset is given as a signed 32-bit integer, the seek would fail at the maximum value of a 32-bit signed int (exactly 2GB, or 2^31).

**Comment by Stephen-Seo** [comment]
I made [another commit to my fork](https://github.com/Stephen-Seo/webfsd/commit/4f1783339ff5b1d1eeb6729d6f857d5f63c42e3a) because my "fix" broke resuming incomplete file downloads since it removed `lseek`. The new fix is using `off_t` instead of an `int` which on my 64-bit machine is a 64-byte integer, so the new max-size of file downloads is the maximum value of that type. Since this new commit is nearly identical to the original implementation (just integer types changed for the `ssl_blk_write` function), I think its good enough for a pull request, which I will do.

**Comment by ourway** [comment]
Well, I tested it and it seems OK. Thank you.
