### ISSUE TITLE
Cannot change document root

### ISSUE THREAD

**Issue by wallyreport** [ourway/webfsd#6]
```
#uname -a
Linux fir.nuclix 5.3.0-3parrot3-amd64 #1 SMP Parrot 5.3.9-3parrot3 (2019-11-23) x86_64 GNU/Linux
```

```
#webfsd -h
-r dir   document root is >dir< 

#webfsd -r ~/webdocs
bind: Address already in use
```

```
# vim /etc/webfsd.conf

# document root
web_root="/home/myhomedir/webdocs"

#service webfs stop
#service webfs start
```

Fails again. It still uses /var/www/html as the document root.

Any ideas?

**Comment by adiroiban** [comment]
Most probably the port is already used.

set `web_port="12345"` or some other free port in /etc/webfsd.conf  and you should have your server running on that port.

I think that this is not an issue and it should be closed.

**Comment by ErSoul** [comment]
The service script (in /etc/init.d/webfs) is the problem. It doesn't stops or reload the daemon. You must kill the process and then start it again.
