### ISSUE TITLE
Some characters show garbled codes

### ISSUE THREAD

**Issue by PhymurByrd** [ourway/webfsd#8]
Should add utf-8 setting in the html header:

<head><title>%s:%d%s</title>**<meta charset=\"utf-8\">**</head> ?

**Comment by ourway** [comment]
why? could you please explain more?

**Comment by monyxie** [comment]
Hi, I encountered the same problem and I think I can provide some explanation.

Web contents could be encoded in many encodings like UTF-8, UTF-16, GB18030 and so on. And like-wise, filenames could also be encoded in different encodings. In order for browsers to render the contents correctly, the web server must provide the encoding of its content to the browser. This could be done either via a [meta tag with the "charset" attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#attr-charset), or via a [Content-Type header with the "charset" directive](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type). If the encoding is not provided, the content could be rendered as garbled text in the browser.

For example, this is how a directory listing page look like in Firefox, generated by webfsd:
![screenshot-200819105625](https://user-images.githubusercontent.com/703164/90587268-8c9f7700-e20b-11ea-8db5-342c421864ab.png)

And this is how it is supposed to look like: 
![screenshot-200819105701](https://user-images.githubusercontent.com/703164/90587401-dd16d480-e20b-11ea-963d-008d984a3fbd.png)
(this is achieved by manually choosing the correct encoding in Firefox, Chrome doesn't even provide such functionality anymore)

So it would be really nice if webfs could:
* Guess the encoding from the environment and/or use UTF-8 as the default encoding
* Provide an option to manually overwrite the encoding
* Set the encoding in HTTP response, either via the meta tag or via the Content-Type header.

**Comment by PhymurByrd** [comment]
Nice~

**Comment by tsingkong** [comment]
why this ticket is closed
